tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
brew "readline"
brew "sqlite"
brew "ansible"
brew "autoconf"
brew "automake"
brew "coreutils"
brew "git"
brew "hugo"
brew "libksba"
brew "libtool"
brew "mas", link: false
brew "nmap"
brew "node"
brew "pkg-config"
brew "python", link: false
brew "sshpass"
brew "tree"
brew "zlib"
cask "font-hack-nerd-font"
cask "font-monoid-nerd-font"
cask "github"
cask "iterm2"
cask "powershell"
cask "visual-studio-code"
